# data loader configuration
data:
  dataset: "amazon"
  batch_size: 2048
  normalize_data: False
  category: "beauty"
  split: "all"

# model configuration (RQ-VAE)
model:
  quantizer_type: "rqvae"
  input_dimension: 768
  hidden_dimensions: [768, 256, 128]
  latent_dimension: 64            # GRID used 64; TIGER used 32
  codebook_layers: 3
  codebook_size: 128
  commitment_weight: 0.25         # GRID used 0.25
  quantization_method: "ste"
  distance_method: "l2"
  normalize_inputs: True          # VAE model-internal input normalization layer (BatchNorm + L2 Norm)

# training configuration (RQ-VAE)
train:
  optimizer: "adagrad"
  learning_rate: 1e-3
  weight_decay: 0
  num_epochs: 2000
  use_lr_scheduler: False

# additional configuration
general:
  seed: 10
  use_wandb: True
  wandb_log_artifacts: False
  wandb_project_quantizer: "mt-amazon-quantizer"
  wandb_entity: "tobias-mueller99-johannes-kepler-universit-t-linz"
  save_model: True
