# data loader configuration
data:
  dataset: "amazon"
  batch_size: 1024
  normalize_data: False
  category: "beauty"
  split: "all"

# model configuration (RQ-VAE)
model:
  input_dimension: 768
  hidden_dimensions: [512, 256, 128]
  latent_dimension: 32            # GRID used 64; TIGER used 32
  num_codebook_layers: 3
  codebook_clusters: 256
  commitment_weight: 0.25         # GRID used 0.25
  quantization_method: "ste"
  distance_method: "l2"

# training configuration (RQ-VAE)
train:
  seed: 10
  optimizer: "adagrad"
  learning_rate: 1e-3             # TIGER paper states 0.4, but this is likely a typo (GRID used 1e-3, and 0.4 is very high for Adagrad)
  weight_decay: 0
  num_epochs: 2000
  use_lr_scheduler: False
  warmup_steps: 1000
  min_lr_ratio: 0.01
  temperature_annealing: True
  temperature_update_frequency: 1
  annealing_schedule: "cosine"
  temperature: 1.0
  min_temperature: 0.5
  temperature_decay: 0.995

# additional configuration
general:
  use_wandb: True
  wandb_project_rqvae: "mt-amazon-rqvae"
  wandb_entity: "tobias-mueller99-johannes-kepler-universit-t-linz"
  save_model: True
